### ISSUE TITLE
why did you do in this manner?

### ISSUE THREAD

**Issue by sunnnnnnnny** [cornerfarmer/ctc_segmentation#2]
Hello, I am very grateful for your work. The result is really good. After reading the paper four or five times, I still feel very confused; especially the `equations (1) and (2)` in it. The work relies on the undecoded path graph obtained by the `encoder` model. So how does an encoder-decoder with ctc and attention speech recognition model help the segmentation precision?

**Comment by lumaku** [comment]
CTC carries over the concept of [Hidden Markov Models](https://en.wikipedia.org/wiki/Hidden_Markov_model) over to end-to-end neural networks and provides a way to make the model differentiable. Using the frame-wise probabilities that are given by a CTC-trained model, the algorithm is comparable to the [forward-backward algorithm](https://en.wikipedia.org/wiki/Forward%E2%80%93backward_algorithm) with (1) as its forward and (2) as its backward part.

> So how does an encoder-decoder with ctc and attention speech recognition model help the segmentation precision?

When doing speech recognition with an attention mechanism, the attention mechanism sometimes misplaces its attention focus. In a hybrid CTC/attention system, CTC provides the information at which point in time a certain token occurs and therefore "aligns" the attention decoding. This, however, is only valid for speech recognition - attention is not important at all for CTC segmentation. For CTC segmentation, you only need the CTC part. It doesn't need a hybrid CTC/attention model, but you could use a CTC-only Deepspeech model as well.
