### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ekmb** [cornerfarmer/ctc_segmentation#3]
Very impressive work!

The repo doesn't include any license file although the files you added to the espnet repo mention Apache 2.0 license. Would it possible to add license to this project?

Thanks.

**Comment by lumaku** [comment]
Thank you!

We will update the repository after the presentation at the SPECOM conference to also include a license.
This repository contains contains the source code used in the paper. A maintained version of the CTC segmentation algorithm is in:
https://github.com/lumaku/ctc-segmentation
It contains the code to the ctc_segmentation python package: `pip install ctc-segmentation`
If you want to make modifications or improvements to the algorithm, you can also send an email/message to me (email address on paper) to discuss improvements or send a pull request.

If you want to integrate CTC segmentation into your CTC-based net, I recommend to take a look at `asr_align.py` in ESPnet for a blueprint how to do it. It's already integrated into the toolkit.

**Comment by ekmb** [comment]
Thank you!
