### ISSUE TITLE
word-based alignments?

### ISSUE THREAD

**Issue by abnerLing** [cornerfarmer/ctc_segmentation#4]
is it possible to get the word-based alignments instead of full utterance?

**Comment by cornerfarmer** [comment]
Yes that is possible, but you need therefore to manually extend the code:

In line 216 of align.py:
https://github.com/cornerfarmer/ctc_segmentation/blob/4c8309652fc5af3d4a970b8e9d3f3ba0c90e855d/align.py#L216

the variable `timings` contains for every character in `ground_truth`

https://github.com/cornerfarmer/ctc_segmentation/blob/4c8309652fc5af3d4a970b8e9d3f3ba0c90e855d/align.py#L115

the alignment in seconds.

Based on that it should be possible to get to word-based-alignments.

**Comment by abnerLing** [comment]
@cornerfarmer thank you very much, I got it.
