### ISSUE TITLE
where is the exp/tedlium2_rnn/cmvn.ark from?

### ISSUE THREAD

**Issue by HalFTeen** [cornerfarmer/ctc_segmentation#5]
hi，I have run the program according to the README. now I want to use another model in ESPnet Model Zoo, but "cmvn.ark" is not included in the zip file. I wonder how can i get the cmvn.ark, and what is it used for? THX.

**Comment by cornerfarmer** [comment]
Its contains the parameters used for `Cepstral Mean and Variance Normalization`, i.e. normalization of the input audio. It is usually created based on the training data, so its specific to the training procedure of your model.

In espnet it is usually computed like that: https://github.com/espnet/espnet/blob/master/egs/tedlium3/asr1/run.sh#L110

**Comment by lumaku** [comment]
Yes! The `cvmn.ark` is specific to the model and dataset. For ESPnet 1 models, it is a separate file. The code in this repository was programmed using espnet 1.

However, the _ESPnet Model Zoo_ contains models for espnet 2. Model files for espnet 2 already include the CMVN parameters in the model file.

Using espnet 1 or 2 should give similar results for CTC segmentation, however, I think that espnet 2 is much more user-friendly. There is currently a pending pull request for CTC segmentation in espnet 2, see here: espnet/espnet#3087 
If you already want to use espnet2, you can try it out after you downloaded the code, for example with a git checkout from the feature branch. Also, I would be happy if you give feedback, what model you used and how well it works with your setup.

**Comment by HalFTeen** [comment]
> Yes! The `cvmn.ark` is specific to the model and dataset. For ESPnet 1 models, it is a separate file. The code in this repository was programmed using espnet 1.
> 
> However, the _ESPnet Model Zoo_ contains models for espnet 2. Model files for espnet 2 already include the CMVN parameters in the model file.
> 
> Using espnet 1 or 2 should give similar results for CTC segmentation, however, I think that espnet 2 is much more user-friendly. There is currently a pending pull request for CTC segmentation in espnet 2, see here: [espnet/espnet#3087](https://github.com/espnet/espnet/pull/3087)
> If you already want to use espnet2, you can try it out after you downloaded the code, for example with a git checkout from the feature branch. Also, I would be happy if you give feedback, what model you used and how well it works with your setup.
----
thank you so much! I'll try to use espnet2.

**Comment by lumaku** [comment]
@HalFTeen CTC segmentation for Espnet 2 was merged a while ago. I hope it worked for you!
